# Generated by Django 6.0 on 2025-12-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_scheduleresult_group_id_alter_subject_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='fix_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='fix_slot',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
