# Generated by Django 6.0 on 2026-02-01 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_subject_fix_day_subject_fix_slot_subject_is_fixed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleresult',
            options={'verbose_name': 'ผลการจัดตาราง', 'verbose_name_plural': 'ผลการจัดตาราง'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'รายวิชา', 'verbose_name_plural': 'รายวิชา'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'ครูผู้สอน', 'verbose_name_plural': 'ครูผู้สอน'},
        ),
        migrations.AddField(
            model_name='scheduleresult',
            name='subject_name',
            field=models.CharField(default='', max_length=100, verbose_name='ชื่อวิชา'),
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=0, verbose_name='หน่วยกิต (น)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_hours',
            field=models.IntegerField(default=0, verbose_name='ปฏิบัติ (ป)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='theory_hours',
            field=models.IntegerField(default=0, verbose_name='ทฤษฎี (ท)'),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='day',
            field=models.IntegerField(verbose_name='วัน (1-5)'),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='group_id',
            field=models.CharField(max_length=50, verbose_name='กลุ่มเรียน'),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='room',
            field=models.CharField(max_length=50, verbose_name='ห้องเรียน'),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='slot',
            field=models.IntegerField(verbose_name='คาบเรียน'),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='subject_code',
            field=models.CharField(max_length=20, verbose_name='รหัสวิชา'),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='teacher_name',
            field=models.CharField(max_length=100, verbose_name='ชื่อผู้สอน'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, verbose_name='รหัสวิชา'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fix_day',
            field=models.IntegerField(default=1, verbose_name='วันที่ล็อค'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fix_slot',
            field=models.IntegerField(default=1, verbose_name='คาบที่ล็อค'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fixed_room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ห้องเรียนประจำ'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group_id',
            field=models.CharField(max_length=50, verbose_name='กลุ่มเรียน'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='hours_per_week',
            field=models.IntegerField(default=1, verbose_name='ชั่วโมง/สัปดาห์ (ช)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='ล็อคคาบ'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อวิชา'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.teacher', verbose_name='ครูผู้สอน'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อผู้สอน'),
        ),
    ]
