# Generated by Django 6.0 on 2026-02-01 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_scheduleresult_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.AddField(
            model_name='scheduleresult',
            name='subject_details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='group_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='room',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='slot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduleresult',
            name='teacher_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fix_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fix_slot',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fixed_room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='group_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subject',
            name='hours_per_week',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practical_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='theory_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
