# Generated by Django 6.0 on 2026-02-01 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_scheduleresult_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อห้อง')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='ชื่อกลุ่มเรียน')),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='group_id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, verbose_name='รหัสวิชา'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(default=0, verbose_name='หน่วยกิต'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fix_day',
            field=models.IntegerField(default=1, verbose_name='วันที่ล็อก (1-5)'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fix_slot',
            field=models.IntegerField(default=1, verbose_name='คาบที่ล็อก'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='hours_per_week',
            field=models.IntegerField(default=1, verbose_name='ชั่วโมง/สัปดาห์'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='ล็อกเวลาเรียน'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อวิชา'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practical_hours',
            field=models.IntegerField(default=0, verbose_name='ปฏิบัติ'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.teacher', verbose_name='อาจารย์ผู้สอน'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='theory_hours',
            field=models.IntegerField(default=0, verbose_name='ทฤษฎี'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ชื่ออาจารย์'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fixed_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.room', verbose_name='ห้องประจำ'),
        ),
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.studentgroup', verbose_name='กลุ่มเรียน'),
        ),
    ]
