# Generated by Django 6.0 on 2026-02-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_room_name_alter_scheduleresult_group_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleresult',
            name='subject_details',
        ),
        migrations.AlterField(
            model_name='subject',
            name='fix_day',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fix_slot',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
