# Generated by Django 6.0 on 2026-02-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_scheduleresult_subject_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสวิชา')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อวิชา')),
                ('theory_hours', models.IntegerField(default=0, verbose_name='ทฤษฎี')),
                ('practical_hours', models.IntegerField(default=0, verbose_name='ปฏิบัติ')),
                ('credits', models.IntegerField(default=0, verbose_name='หน่วยกิต')),
            ],
        ),
    ]
