# Generated by Django 6.0 on 2026-02-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_mastersubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersubject',
            name='practical_hours',
            field=models.IntegerField(default=0, verbose_name='ปฏิบัติ (ชม.)'),
        ),
        migrations.AlterField(
            model_name='mastersubject',
            name='theory_hours',
            field=models.IntegerField(default=0, verbose_name='ทฤษฎี (ชม.)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ชื่อห้อง'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ชื่อกลุ่มเรียน'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fix_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fix_slot',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อครูผู้สอน'),
        ),
    ]
